### ISSUE TITLE
OpenLdap support for sonarw

### ISSUE THREAD

**Issue by arthurJsonar** [jsonar/cmake#38]
@pablojSonar is rewriting our LDAP support, this time using openldap.

He wrote a test program and to compile it he wrote the following `CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.10)

project(ldap_test)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake/")
find_package(OpenLdap REQUIRED)

include_directories(include)
file(GLOB SOURCES "source/*.cpp")

add_executable(ldap_test ${SOURCES} source/main.cpp)
target_link_libraries(ldap_test ldap)
```

And this is `OpenLdap.cmake`:

```
find_path(OPENLDAP_INCLUDE_DIR ldap.h PATHS
  /usr/include
  /opt/local/include
  /usr/local/include)

find_library(LDAP_LIBRARY ldap)
find_library(LBER_LIBRARY lber)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OpenLdap DEFAULT_MSG
  OPENLDAP_INCLUDE_DIR LDAP_LIBRARY LBER_LIBRARY)

set(OPENLDAP_LIBRARIES ${LDAP_LIBRARY} ${LBER_LIBRARY})

mark_as_advanced(
  OPENLDAP_INCLUDE_DIR LDAP_LIBRARY LBER_LIBRARY)
```

I told him to start changing sonarw using the system library and just doing minimal changes to the cmake, but we need this OpenLDAP library linked statically just like all other libraries.

**Comment by yhagerjs** [comment]
How did you guys install openldap?

**Comment by pablojSonar** [comment]
sudo yum install openldap-devel

**Comment by yhagerjs** [comment]
which version?

**Comment by pablojSonar** [comment]
In my machine it installed `2.4.44-21.el7_6`

**Comment by yhagerjs** [comment]
That's an ancient version (from 2016). Any reason you prefer this one and not the latest, 2.4.55?

**Comment by pablojSonar** [comment]
No reason at all. It was the version that `yum` installed on my machine

**Comment by arthurJsonar** [comment]
@yhagerjs the sonarw code is ready (actually under review) https://github.com/jsonar/sonarw/pull/6732

do you have a estimate for your part?

**Comment by yhagerjs** [comment]
usually it's very quick, but I haven't looked into the details yet. I am planning to work on it tomorrow (Oct 31st)

**Comment by eranjsonar** [comment]
@yhager  this is critical for 4.2.f 
Please give it a high priority

**Comment by yhagerjs** [comment]
🤬

**Comment by yhagerjs** [comment]
Fixed. Link to `openldap::ldap` and/or `openldap::lber`
